# Generated by Django 5.1.7 on 2025-04-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место выполнения')),
                ('habit_time', models.TimeField(verbose_name='Время выполнения привычки')),
                ('habit_action', models.CharField(max_length=100, verbose_name='Действие')),
                ('is_habit_pleasantly', models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак приятной привычки')),
                ('habit_periodicity', models.PositiveIntegerField(verbose_name='Периодичность привычки')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Награда')),
                ('habit_time_to_complete', models.PositiveIntegerField(default=120, verbose_name='Время на выполнение')),
                ('is_habit_public', models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак публичности')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
